# Control Plane VM for cks CKS Environment
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: ${CONTROL_PLANE_VM_NAME}
  namespace: ${SESSION_NAMESPACE}
  labels:
    app: cks
    role: control-plane
    session: ${SESSION_ID}
    k8s-version: "${K8S_VERSION}"
spec:
  running: true
  template:
    metadata:
      labels:
        app: cks
        role: control-plane
        session: ${SESSION_ID}
    spec:
      domain:
        resources:
          requests:
            memory: ${MEMORY}
            cpu: ${CPU_CORES}
          limits:
            memory: ${MEMORY}
            cpu: ${CPU_CORES}
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - name: default
              bridge: {}
      networks:
        - name: default
          pod: {}
      volumes:
        - name: rootdisk
          dataVolume:
            name: ${CONTROL_PLANE_VM_NAME}-rootdisk
        - name: cloudinitdisk
          cloudInitNoCloud:
            secretRef:
              name: ${CONTROL_PLANE_VM_NAME}
            networkData: |
              version: 2
              ethernets:
                enp1s0:
                  dhcp4: true
                  dhcp-identifier: mac
---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: ${CONTROL_PLANE_VM_NAME}-rootdisk
  namespace: ${SESSION_NAMESPACE}
spec:
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: ${STORAGE_SIZE}
    storageClassName: ${STORAGE_CLASS}
  source:
    pvc:
      namespace: ${GOLDEN_IMAGE_NAMESPACE}
      name: ${GOLDEN_IMAGE_NAME}
